services:
  kaggle:
    build:
      dockerfile: ./Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
        - PROJECT=${PROJECT}
    restart: always
    tty: true
    volumes:
      - .:/workspace
      - /workspace/projects/${PROJECT}/.venv
    ipc: host
    ulimits:
      memlock: -1
      stack: -1
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
