line-length = 120
indent-width = 4
target-version = "py312"
output-format = "grouped"

[lint]
ignore = [
	"D103",
	"D100", # ignore missing docstring in module
	"D102", # ignore missing docstring in public method
	"D104", # ignore missing docstring in public package
	"D105", # ignore missing docstring in magic methods
	"D107", # ignore missing docstring in __init__ methods
]
extend-select = ["Q", "RUF100", "C90", "UP", "I", "D"]
isort = { combine-as-imports = true }
mccabe = { max-complexity = 15 }


[lint.pydocstyle]
convention = "google"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
