name: ci

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.py'

permissions:
  pull-requests: write

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          install: true

      - name: Run Ruff Format
        run: mise run ci-format

      - name: Run Ruff Lint
        run: mise run ci-lint

  mypy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: jdx/mise-action@v2
          with:
            install: true
        - name: Run mypy
          run: mise run ci-type-check
